services:
  app:
    build:
      context: ./app         # ⬅️ پوشه app رو به عنوان context بده
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: polls

  redis:
    image: redis:alpine
